### PR TITLE
detector: Remove deprecated use of zk.StateSyncConnected

### LINKED ISSUE #143: go get fails for detector/zoo
Running `go get github.com/mesos/mesos-go/detector/zoo` fails because of a change to https://github.com/samuel/go-zookeeper that removed `zk.StateSyncConnected`:

```
root@5fd256b1691e:/dev# go get github.com/mesos/mesos-go/detector/zoo
# github.com/mesos/mesos-go/detector/zoo
/go/src/github.com/mesos/mesos-go/detector/zoo/client.go:273: undefined: zk.StateSyncConnected
root@5fd256b1691e:/dev#
```
The offending commit is here: https://github.com/samuel/go-zookeeper/commit/9cffda5bbd55d2b6f9cd11ebec92a32a79699605)

### PR DESCRIPTION
**Pull request by sttts**
Fixes #143

### CODE REVIEW

**Comment by tsenart** [comment]
Thanks for the PR @sttts.

**Comment by sttts** [comment]
Do we have wrong gedeps references anywhere which must be updated? I am still a bit confused why old git commits referenced with godeps show this breakage at all.

**Comment by tsenart** [comment]
Since this is a library, I don't even know why we have a Godeps directory
there. Libraries can't vendor code in a sane way. That's the responsibility
of integrators.

**Comment by sttts** [comment]
Yes, but I meant mesos-DNS and others. Will check the former.
