### ISSUE TITLE
go get fails for detector/zoo

### ISSUE THREAD

**Issue by tomfaulhaber** [mesos/mesos-go#143]
Running `go get github.com/mesos/mesos-go/detector/zoo` fails because of a change to https://github.com/samuel/go-zookeeper that removed `zk.StateSyncConnected`:

```
root@5fd256b1691e:/dev# go get github.com/mesos/mesos-go/detector/zoo
# github.com/mesos/mesos-go/detector/zoo
/go/src/github.com/mesos/mesos-go/detector/zoo/client.go:273: undefined: zk.StateSyncConnected
root@5fd256b1691e:/dev#
```
The offending commit is here: https://github.com/samuel/go-zookeeper/commit/9cffda5bbd55d2b6f9cd11ebec92a32a79699605)

**Comment by yufeldman** [comment]
Is anybody plans to fix this issue?

**Comment by hanwang** [comment]
Confirming that this is breaking the recommended mesos-dns build method.

**Comment by milosgajdos83** [comment]
I'm seeing the same issue. Slightly annoying :-)

**Comment by rtyer** [comment]
+1

**Comment by tsenart** [comment]
PTAL everyone, /cc @spacejam @sttts

**Comment by sttts** [comment]
LGTM

**Comment by tsenart** [comment]
Thanks everyone for raising awareness on this issue. In general, we'll have to give more love to mesos-go in the near future. There are very many things that need attention but haven't been priorities. We hope to change that :-)

**Comment by tomfaulhaber** [comment]
Thanks for getting this resolved so quickly!

**Comment by milosgajdos83** [comment]
Thank you for quick resolution! :+1:
